#!/usr/bin/env python3
"""
A function that generates a detailed classification report using Scikit-learn

Arguments:
true_labels: Ground truth labels
predicted_labels: Predicted labels
class_names: List of class names corresponding to the label indices

Returns:
A string containing the classification report generated by Scikit-learn.
"""
from sklearn import metrics


def evaluate(true_labels, predicted_labels, class_names):
    """
    A function to generate predictions from a trained tree-based classifier
    """

    return metrics.classification_report(
            true_labels,
            predicted_labels,
            target_names=class_names.tolist()
    )
